[project]
name = "lawscraper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
]

[tool.uv.workspace]
members = ["ohio_administration", "ohio_revised", "ohio_constitution", "packages/utils",  "ohio_case_law"]
